### ISSUE TITLE
cannot run on Debian/Ubuntu

### ISSUE THREAD

**Issue by salmanishere** [ebrahimraeyat/civilTools#12]
When I try to run your software on either Debian or Ubuntu, I get the following error:

```
ImportError: No module named PyQt5.QtCore
```

**Comment by salmanishere** [comment]
You need to change `python_exe = 'python'`to `python_exe = 'python3'`. I can do it in a pull request.

**Comment by ebrahimraeyat** [comment]
Thanks @salmanishere .
but you almost want to create virtual env on your machin. because you must install extra packages that maybe you can't install on your wide system.

**Comment by salmanishere** [comment]
no, that is not the same issue! 

On Debian-based distros (Debian, Ubuntu, etc), the **default** system-wide `python` is linked to `python2`, so if you use the `python` you will be using python2.

On a Debian Stretch (stable version) machine:

```
$ ls -l /usr/bin/python
lrwxrwxrwx 1 root root 9 Jan 24  2017 /usr/bin/python -> python2.7

$ ls -l /usr/bin/python3
lrwxrwxrwx 1 root root 9 Jan 20  2017 /usr/bin/python3 -> python3.5
```

**Comment by salmanishere** [comment]
I improved the code to check the python interpreter version at startup. In this way, we can check if we are using the correct one or not.
