### ISSUE TITLE
your git tags have disappeared

### ISSUE THREAD

**Issue by salmanishere** [ebrahimraeyat/civilTools#14]
I was watching one of your videos, that saw your git repo has had tags, but currently none are left. Did you intentionally remove them?

**Comment by salmanishere** [comment]
I mean in this video.

![github-tags](https://user-images.githubusercontent.com/45880325/51915408-4f7e5480-23db-11e9-93b0-81398c978061.png)

**Comment by ebrahimraeyat** [comment]
oh, yes. because in those tags update push button was disable. and when user back to that tag they coudn't back to the latest version. I removed them.

**Comment by salmanishere** [comment]
generally, you shouldn't have had problem. What was the error? As I can see in the video, which you have posted here: https://t.me/civiltools/288 you could also do it with no problem.

**Comment by ebrahimraeyat** [comment]
Yes, i can, but i mean for end users!

**Comment by salmanishere** [comment]
If you have problems, we can implement a function to solve it.

**Comment by ebrahimraeyat** [comment]
Thanks. but for all of my users it's not important that could back to previous version!
