### ISSUE TITLE
گزارش ایراد و درخواست جهت رفع نقص نرم افزار مقطع ساز سیویل

### ISSUE THREAD

**Issue by AliranjbarCivil** [ebrahimraeyat/civilTools#5]
درود خدمت جناب آقای مهندس
با تشکر از حضرتعالی بابت آپدیت آخرین ورژن 1.5 نرم افزار 
در هنگام کار با نسخه جدید متوجه بسته شدن محیط نرم افزار در قسمت انتخاب ورق های تقویتی شدم؛ در صورت امکان مورد را بررسی و رفع نقص نمایید
ممنون

**Comment by ebrahimraeyat** [comment]
سلام خدمت شما مهندس جان.
ممنون بابت پیگیری مجدانه و گزارش ایرادها.
ایراد رو رفع کردم. میتونید فایل اصلاح شده رو دانلود کنید، اینجا
https://github.com/ebrahimraeyat/civilTools/commit/c8a0891f2329cd520f26c4cca8e69a3188e5f71f

**Comment by ebrahimraeyat** [comment]
سلام مهندس جان. توی نسخه جدید این ایراد رو رفع کردم.
